import { writeFileSync } from "node:fs";
import { converter, formatHex, inGamut, wcagContrast } from "culori";
import { APCAcontrast, sRGBtoY } from "apca-w3";
const colors = {
  background: [0.986, 0.005, 255],
  foreground: [0.25, 0.028, 255],
  card: [0.994, 0.001, 255],
  "card-foreground": [0.25, 0.028, 255],
  popover: [0.994, 0.001, 255],
  "popover-foreground": [0.25, 0.028, 255],
  primary: [0.425, 0.085, 255],
  "primary-foreground": [0.992, 0.003, 255],
  secondary: [0.938, 0.018, 255],
  "secondary-foreground": [0.32, 0.045, 255],
  muted: [0.956, 0.013, 255],
  "muted-foreground": [0.435, 0.024, 255],
  accent: [0.927, 0.026, 255],
  "accent-foreground": [0.32, 0.045, 255],
  destructive: [0.47, 0.16, 25],
  border: [0.853, 0.022, 255],
  input: [0.635, 0.035, 255],
  ring: [0.425, 0.085, 255],
  "surface-alt": [0.967, 0.008, 255],
  "hero-background": [0.275, 0.038, 255],
  "hero-foreground": [0.985, 0.004, 255],
  "hero-muted": [0.84, 0.025, 255],
  "hero-dot": [0.55, 0.041, 255],
  "hero-border": [0.495, 0.034, 255],
  "data-people": [0.425, 0.085, 255],
  "data-relationships": [0.495, 0.09, 72],
  "data-secondary": [0.665, 0.12, 78],
  "data-unknown": [0.53, 0.02, 255],
  "section-marker": [0.59, 0.04, 255],
  "map-highlight": [0.56, 0.11, 70],
  "map-missing": [0.855, 0, 0],
  "notice-background": [0.963, 0.026, 85],
  selection: [0.878, 0.048, 255],
  "map-1": [0.9, 0.029, 255],
  "map-2": [0.79, 0.054, 255],
  "map-3": [0.68, 0.079, 255],
  "map-4": [0.57, 0.095, 255],
  "map-5": [0.46, 0.099, 255],
  "map-6": [0.35, 0.079, 255],
};
const rgb = converter("rgb");
const palette = Object.fromEntries(
  Object.entries(colors).map(([name, [l, c, h]]) => {
    const value = { mode: "oklch", l, c, h };
    if (!inGamut("rgb")(value)) throw new Error(`Out of sRGB gamut: ${name}`);
    return [name, { css: `oklch(${l} ${c} ${h})`, hex: formatHex(value) }];
  }),
);
const pairs = [
  ["foreground", "background", 75],
  ["muted-foreground", "background", 75],
  ["muted-foreground", "muted", 75],
  ["foreground", "card", 75],
  ["primary-foreground", "primary", 60],
  ["hero-foreground", "hero-background", 75],
  ["hero-muted", "hero-background", 60],
  ["primary", "muted", 60],
  ["secondary-foreground", "secondary", 75],
  ["accent-foreground", "accent", 75],
  ["muted-foreground", "surface-alt", 75],
];
const luminance = (name) => {
  const v = rgb(palette[name].css);
  return sRGBtoY([v.r * 255, v.g * 255, v.b * 255]);
};
const contrast = pairs.map(([fg, bg, min]) => {
  const ratio = wcagContrast(palette[fg].css, palette[bg].css);
  const apca = Math.abs(APCAcontrast(luminance(fg), luminance(bg)));
  if (ratio < 4.5 || apca < min) throw new Error(`${fg} on ${bg}: WCAG ${ratio}, APCA ${apca}`);
  return { foreground: fg, background: bg, wcagRatio: +ratio.toFixed(2), apcaLc: +apca.toFixed(1) };
});
const graphics = [
  ["hero-dot", "hero-background"],
  ["data-secondary", "hero-background"],
  ["section-marker", "background"],
  ["input", "background"],
].map(([fg, bg]) => {
  const ratio = wcagContrast(palette[fg].css, palette[bg].css);
  if (ratio < 3) throw new Error(`${fg} on ${bg}: graphic contrast ${ratio}`);
  return { foreground: fg, background: bg, wcagRatio: +ratio.toFixed(2) };
});
const css = `/* Generated by scripts/build_theme.mjs. Edit the OKLCH palette there. */\n:root {\n${Object.entries(
  palette,
)
  .map(([name, p]) => `  --${name}: ${p.css};`)
  .join("\n")}\n  --radius: 0.625rem;\n}\n@theme inline {\n${Object.keys(palette)
  .map((name) => `  --color-${name}: var(--${name});`)
  .join(
    "\n",
  )}\n  --radius-sm: calc(var(--radius) - 4px);\n  --radius-md: calc(var(--radius) - 2px);\n  --radius-lg: var(--radius);\n  --radius-xl: calc(var(--radius) + 4px);\n}\n`;
writeFileSync(new URL("../src/theme.css", import.meta.url), css);
writeFileSync(
  new URL("../src/lib/palette.json", import.meta.url),
  JSON.stringify(palette, null, 2) + "\n",
);
writeFileSync(
  new URL("../data/color-validation.json", import.meta.url),
  JSON.stringify({ gamut: "sRGB", contrast, graphics }, null, 2) + "\n",
);
console.log(JSON.stringify(contrast, null, 2));
