/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1DataRouteImport } from './routes/api.v1.data'
import { Route as ApiV1MetaRouteImport } from './routes/api.v1.meta'
import { Route as ApiV1RegionsRouteImport } from './routes/api.v1.regions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DataRoute = ApiV1DataRouteImport.update({
  id: '/api/v1/data',
  path: '/api/v1/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetaRoute = ApiV1MetaRouteImport.update({
  id: '/api/v1/meta',
  path: '/api/v1/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RegionsRoute = ApiV1RegionsRouteImport.update({
  id: '/api/v1/regions',
  path: '/api/v1/regions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/data': typeof ApiV1DataRoute
  '/api/v1/meta': typeof ApiV1MetaRoute
  '/api/v1/regions': typeof ApiV1RegionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/data': typeof ApiV1DataRoute
  '/api/v1/meta': typeof ApiV1MetaRoute
  '/api/v1/regions': typeof ApiV1RegionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/data': typeof ApiV1DataRoute
  '/api/v1/meta': typeof ApiV1MetaRoute
  '/api/v1/regions': typeof ApiV1RegionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/v1/data' | '/api/v1/meta' | '/api/v1/regions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/v1/data' | '/api/v1/meta' | '/api/v1/regions'
  id: '__root__' | '/' | '/api/v1/data' | '/api/v1/meta' | '/api/v1/regions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1DataRoute: typeof ApiV1DataRoute
  ApiV1MetaRoute: typeof ApiV1MetaRoute
  ApiV1RegionsRoute: typeof ApiV1RegionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/data': {
      id: '/api/v1/data'
      path: '/api/v1/data'
      fullPath: '/api/v1/data'
      preLoaderRoute: typeof ApiV1DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/meta': {
      id: '/api/v1/meta'
      path: '/api/v1/meta'
      fullPath: '/api/v1/meta'
      preLoaderRoute: typeof ApiV1MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/regions': {
      id: '/api/v1/regions'
      path: '/api/v1/regions'
      fullPath: '/api/v1/regions'
      preLoaderRoute: typeof ApiV1RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1DataRoute: ApiV1DataRoute,
  ApiV1MetaRoute: ApiV1MetaRoute,
  ApiV1RegionsRoute: ApiV1RegionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
